### ISSUE TITLE
Create K30 Examples And App Notes

### ISSUE THREAD

**Issue by nathanafox-us** [co2meter-org/ExampleCode#1]
## Problem
The K30 is the sensor that we receive the most calls about. We are creating this GitHub repo to offset some of the calls that we receive so we don't waste as much time dealing with these customers.

## Solution
Put the source code that we want to give them along with the app notes used to run it each into their own folders.

## Todo:
- [x] K30_UART
   - [x] App notes are saved as README.md in the folder with the example code
   - [x] The App notes link to the example code and the repo also contains it
- [x] K30_I2C
   - [x] App notes are saved as README.md in the folder with the example code
   - [x] The App notes link to the example code and the repo also contains it
